### ISSUE TITLE
.dll build instructions or build pipeline

### ISSUE THREAD

**Issue by farmerTheodor** [R2Northstar/Northstar#10]
Would be nice to have .dll build instructions or better yet a build pipeline. This would increase transparency and increase the number of people who might put this on their machine.

**Comment by p0358** [comment]
You just clone the Launcher repo, open in Visual Studio 2022, and compile, not much else to it xd
```
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Then the DLLs from the release can be replaced, and rest of the stuff from the other repos is plaintext anyways

**Comment by MiloAkerman** [comment]
https://github.com/MiloAkerman/NorthstarLauncher/blob/main/BUILD.md

Basically what p0358 said

**Comment by GeckoEidechse** [comment]
Build instructions by @MiloAkerman have since been merged to the Launcher repo. You can find them [here](https://github.com/R2Northstar/NorthstarLauncher/blob/main/BUILD.md)

Closing this issue for now. If the instructions are not clear enough, have errors, or any other problems, please re-open this issue <3
