### ISSUE TITLE
Fastball on LiveFire maps crashes the lobby

### ISSUE THREAD

**Issue by VIZaneIV** [R2Northstar/Northstar#110]
When starting a game of Fastball on livefire maps generates the following error
![Bez tytułu](https://user-images.githubusercontent.com/72400206/148047419-7dbed95d-7fcf-4c76-b7b6-e1f3096c7235.png)

**Comment by x3Karma** [comment]
Because there's not enough room for BT to spawn in.

**Comment by VIZaneIV** [comment]
Yeah. Selecting Fastball could dissable the option to select LiveFire maps, similarly to atrittion. Or Fastball could be adapted to work there.

**Comment by Neoministein** [comment]
Due to the bug in [#109](https://github.com/R2Northstar/Northstar/issues/109) the locking of the maps aren't correct. If you select Hide and Seek you'll see that the UI states Fastball and the Live Fire maps are locked.

**Comment by GeckoEidechse** [comment]
#109 is fixed with `v1.4.0` and [NorthstarMods#120](https://github.com/R2Northstar/NorthstarMods/pull/120) removed Stacks from the Fastball map rotation (it was the only Live Fire map in there).

I'm not sure if maps not in the map rotation can still be selected in private match. If so, we should at least add some dummy BT positions to at least prevent players from being able to crash servers by selecting Fastball and a Live Fire map.
