### ISSUE TITLE
"Connection Refused" Cant connect to masterserver

### ISSUE THREAD

**Issue by 420basco** [R2Northstar/Northstar#125]
When i open the game the main menu is the vanilla one and i cant pick multiplayer.

looking at the cmd window this is the last thing that pops up after opening the game *   

```
[01:48:20] [info] 0x27337f62000
[01:48:21] [info] Trying to authenticate with northstar masterserver for user (my user ID)
*   Trying 127.0.0.1:80...
[01:48:22] [info] [UI SCRIPT] MainMenuPromos updated
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to 127.0.0.1 port 80 after 2037 ms: Connection refused
* Closing connection 0
[01:48:23] [error] Failed performing northstar origin auth: error Couldn't connect to server
```

![image](https://user-images.githubusercontent.com/91369079/148315584-3348140e-e34f-44e0-b656-b5825ce74a78.png)

started happening in v1.3.0 and still in v1.4.0

  - Northstar version:  1.3.0 an 1.4.0
  - Platform: Windows 10 Steam

**Comment by barnabwhy** [comment]
Why is it connecting to 127.0.0.1:80? Has the master server in config been changed?

**Comment by 420basco** [comment]
idk, this is on a clean install of v1.4.0, i didnt change anything at all in the files

**Comment by 420basco** [comment]
> Why is it connecting to 127.0.0.1:80? Has the master server in config been changed?

idk, this is on a clean install of v1.4.0, i didnt change anything at all in the files

**Comment by Faetan** [comment]
I am also getting this on one of my servers. The other two servers on the same host work fine and all three were working.

Something happened today and the third one is now showing the exact same output even though the configs are correct.

[13:12:30] [info] [SERVER SPEW_MESSAGE] Created new format snapshot class baseline with 78 classes, 7601 properties and 36KB of prop data.
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to 127.0.0.1 port 80 after 2024 ms: Connection refused
* Closing connection 0
[13:12:32] [error] Failed adding self to server list: error Couldn't connect to server

**Comment by Faetan** [comment]
This is the config on the non working one. This was working yesterday.

ns_server_name "[AUS]Chicken Tendies Gaming Hide and Seek // server name
ns_server_desc "discord.gg/JREnGpBK6H Server will auto restart on crash. Join Discord or ping Faetan#9919" // server description
ns_server_password "" // server password
ns_report_server_to_masterserver 1 // whether this server should report itself to the masterserver
ns_report_sp_server_to_masterserver 0 // whether this server should report itself to the masterserver if started on a singleplayer map

ns_auth_allow_insecure 0 // keep this to 0 unless you want to allow people to join without masterserver auth/persistence
ns_erase_auth_info 1 // keep this to 1 unless you're testing and crashing alot, so you don't have to go through the northstar lobby to reauth
ns_player_auth_port 8083 // this can be whatever, make sure it's portforwarded over tcp

ns_masterserver_hostname "https://northstar.tf" // masterserver hostname
everything_unlocked 1 // unlock everything

// gameserver settings
ns_should_return_to_lobby 0 // whether the server should return to private match lobby after completing a game, if 0, this will go to the next map/mode in the playlist
ns_private_match_last_mode "hs"
ns_private_match_last_map "mp_forwardbase_kodai"
ns_private_match_only_host_can_change_settings 2
ns_private_match_countdown_length 10

net_chan_limit_mode 2 // kick clients that go over the limit
net_chan_limit_msec_per_sec 100 // number of milliseconds of server netchan processing time clients can use per second before getting kicked
sv_querylimit_per_sec 10 // number of connectionless packets clients can send to this server per second without getting blocked
base_tickinterval_mp 0.016666667 // default tickrate: 60 tick
sv_updaterate_mp 20 // default updaterate: 20 tick
sv_minupdaterate 20 // unsure if this actually works, but if it does, should set minimum client updaterate
sv_max_snapshots_multiplayer 300 // this needs to be updaterate * 15, or clients will dc in killreplay
net_data_block_enabled 0 // not really sure on this, have heard datablock could have security issues? doesn't seem to have any adverse effects being disabled
host_skip_client_dll_crc  1 // allow people to run modded client dlls, this is mainly so people running pilot visor colour mods can keep those, since they use a client.dll edit
sv_cheats 0
sv_balanceTeams 1
sv_showUserCmds 0

**Comment by Faetan** [comment]
And now after another attempt it decided to work......

**Comment by 420basco** [comment]
after redownloading titanfall 2 and reinstallinhg northstar it fixed itself...

I think it was something to do: either with the vanilla titanfall 2 or something server side
