### ISSUE TITLE
Can you make to where Ps4 users can use Northstar mod as well  

### ISSUE THREAD

**Issue by DFcoop** [R2Northstar/Northstar#151]
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by MaxIsJoe** [comment]
Modding PS4 games is generally difficult and will be a huge headache both the players and modders to get working. By nature Sony disallows modding and even games like Skyrim SE and Fallout 4 modding are verry limited since the content workshop is just a DLC store that bethesda uses.

If you want to play Northstar on your PS4, you can probably install linux by following [a tutorial like this or similar](https://www.youtube.com/watch?v=Ycg-tXPC8lk) and buy the game again through steam and run it via proton **but at the risk of bricking your PS4 if you do anything stupid and much lower performance**

**Comment by GeckoEidechse** [comment]
There is no official push to support Northstar on console at the moment due to both the fact that it is really difficult to do due to the locked down nature of consoles as well as the fact the Sony and Microsoft do not allow mods on consoles and as such any official support could get Northstar into legal trouble.
So as much as we'd love to support consoles so that everyone can play Titanfall 2 again, it's simply not feasible given current circumstances.

That being said, there are efforts made by some community members to support consoles. However everything is in its infancy and no working prototypes exist, so don't expect anything any time soon :/
