### ISSUE TITLE
0 was banned (trying to ban someone sometimes can ban a random person)

### ISSUE THREAD

**Issue by Luna-foxx** [R2Northstar/Northstar#158]
### Bug
when banning someone it will sometimes ban a random person and not the person whos name was typed in
also trying to use the persons uid in the server using the `status` command does the same thing as well
using `status` with uniqueid does not work as well
the 0 id will also show up in the banlist

### Steps to reproduce

  1. in console type `ban <player name>`  example `ban alexa15` or use `ban 5` from status userid
  2. console will output `0 was banned`
  3. random person will then be ban

### Specifications
  - Northstar version: 1.4.0
  - Platform: steam

### TEMP FIX
you can block connections with firewall
status will give player IPs on server console
VPNs are still a thing tho

**Comment by Bobbyperson12** [comment]
I think you have to ban by UID, typing `status` in console will print them

So a correct command would be `ban 12`

**Comment by Bobbyperson12** [comment]
I'd like to confirm that this issue is consistent, on three separate servers I and BulletMemes have tried banning through a variety of means, but it always bans the person in slot 0 (whoever joined first).

Commands we have tried:
`ban name`
`ban "name"`
`ban 1` (join order)
`ban UID` (unique id)

So far the only way to ban the correct person right now it seems is to somehow get their unique id, put it in banlist.txt and restart your server.

**Comment by Luna-foxx** [comment]
hey do we have any way to ban/remove people from a server while this gets fixed?
my server is becoming kinda toxic and i cant do anything about it

**Comment by Luna-foxx** [comment]
TEMP FIX: you can block connections with firewall 
status will give player IPs on server console
VPNs are still a thing tho

**Comment by laundmo** [comment]
i believe the issue with banning the 0th person was fixed here: https://github.com/R2Northstar/NorthstarLauncher/commit/bd2d7e3deadb3d9142630ae633a17b02e2b09fff

**Comment by Luna-foxx** [comment]
i think its still a bug
0 was banned is still happening
also not to be rude
but that was 16 days ago
if it was fixed then this issue would not be a thing

**Comment by BobTheBob9** [comment]
> if it was fixed then this issue would not be a thing

this is in newest github commit, not current release

**Comment by laundmo** [comment]
> also not to be rude but that was 16 days ago if it was fixed then this issue would not be a thing

just to explain some more: on GitHub we track individual changes to the code, those are called commits. They are only code changes for now, for them to end up in your game files there needs to be a new release, thats when the code with all the newest changes is compiled and you can download it. Thats when fixes will actually arrive in your game/server. For now knowing it as fixed in a commit means "come next release this won't be a issue anymore"

**Comment by Luna-foxx** [comment]
ahh yea sorry im kinda new to GitHub thanks for the info
sorry
