### ISSUE TITLE
when is frontier defence coming

### ISSUE THREAD

**Issue by TheHolyTachanka** [R2Northstar/Northstar#185]

**Comment by Vysteria** [comment]
when your mother stops delaying the modders

**Comment by GeckoEidechse** [comment]
No time frame at the moment. We need get working AI nav meshes first which is what tells AI (grunts, spectres, auto-titans, ...) where they can move, otherwise they will just stand still.

Nav mashes are tracked in #3

Check `Modding` -> `research-and-development` -> `navmeshes` on the [Northstar Discord](https://northstar.tf/discord) for current progress.
