### ISSUE TITLE
 Access Violation, unable to keep multiplayer open for more than 5 seconds before it crashes. 

### ISSUE THREAD

**Issue by 99powerbreaker** [R2Northstar/Northstar#187]
### Bug
After playing a game of infection, and crashing, I am now no longer able to play northstar in multiplayer. Multiplayer will work for a few seconds, but not long after will immediately crash. Not sure exactly what I might have done to, but this is consistent crashing. Northstar worked flawlessly before this, but just crashes every time i try to open multiplayer now. 

### Steps to reproduce
Unknown how to initiate this type of behavior.
2. go into northstar multiplayer
3: wait 3 seconds and you get the error message. 

### Specifications
  - Northstar version: v1.4.0
  - Platform: Steam
  - Startup Launch Options: -northstar -novid -noborder -windowed
  - Computer Specs in case that matters: Ryzen 7 5800X, 32GB DDR4 RAM, AMD RX 5700, storage: 2TB Seagate HDD. 
  - OS: Windows 10

[nslog2022-02-09 22-35-06.txt](https://github.com/R2Northstar/Northstar/files/8037896/nslog2022-02-09.22-35-06.txt)
[nslog2022-02-09 22-35-47.txt](https://github.com/R2Northstar/Northstar/files/8037897/nslog2022-02-09.22-35-47.txt)
[nslog2022-02-09 22-28-22.txt](https://github.com/R2Northstar/Northstar/files/8037898/nslog2022-02-09.22-28-22.txt)

https://user-images.githubusercontent.com/99379078/153334048-add14575-d278-47c4-87ef-bcf57605d60c.mp4

**Comment by 99powerbreaker** [comment]
![image](https://user-images.githubusercontent.com/99379078/153336402-81c07935-7349-4f93-ae18-46e3e9aede59.png)
this is also an image of pretty much what everything shows

**Comment by Jeremiah-Roise** [comment]
this is because the Respawn servers were down it can be fixed by not using the advocate network you can change your network by `running communities_hostname ""` in the game console while in main menu.(open the game console by pressing the tilde key the key under the tab key in most cases) if using Linux and the console isn't working see [this fix.](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux#blank-console)

**Comment by BobTheBob9** [comment]
> this is because the Respawn servers were down it can be fixed by not using the advocate network you can change your network by `running communities_hostname ""` in the game console while in main menu.(open the game console by pressing the tilde key the key under the tab key in most cases) if using Linux and the console isn't working see [this fix.](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux#blank-console)

this wasn't because the servers were down, it was an attack done on them that abuses issues in the rson parser to crash clients with malicious openinvites, this was used a few months ago pre-northstar and reported to respawn but i guess it's just still an issue, `communities_hostname ""` prevents any communities stuff from working, which includes networks and openinvites

**Comment by TaBarNeLaCla** [comment]
This was probably repeatedly asked but what if my game console just doesn't open? I tried rebinding the command in the .csg file but it still does not work.
sorry if that is a duplicate question

**Comment by GeckoEidechse** [comment]
Make sure the game is closed while you edit `settings.cfg`. [This section in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/commands#opening-the-console) should tell you which exact config file you'll need to edit.

**Comment by GeckoEidechse** [comment]
Installing the newly released [`v1.4.1`](https://github.com/R2Northstar/Northstar/releases/tag/v1.4.1) should also fix this problem.

**Comment by GeckoEidechse** [comment]
[`v.1.4.2`](https://github.com/R2Northstar/Northstar/releases/tag/v1.4.2) just got released which should solve this for real now  ^^
