### ISSUE TITLE
Frag grenades being thrown prematurely

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#244]
### Bug
There are reports of frag grenades being thrown prematurely. The cause of this needs to be investigated still.

### Steps to reproduce

Not clear yet

### Specifications
  - Northstar version: `v1.6.0`
  - Platform: unspecified (shouldn't matter)

**Comment by GeckoEidechse** [comment]
Recordings showing the bug made by `Iron(real)` on Discord.

https://user-images.githubusercontent.com/40122905/161617120-a557980a-b0ea-4a7f-84be-66aa7ce2a9e3.mp4

https://user-images.githubusercontent.com/40122905/161617129-9dfca4c4-650e-417c-a09c-923a50f2ab05.mp4

https://user-images.githubusercontent.com/40122905/161617214-399afd81-8bae-4a25-b3cb-da8beaf7b033.mp4

https://user-images.githubusercontent.com/40122905/161617229-9dad14d5-d11f-4a97-a85f-fc0d78b5d521.mp4

https://user-images.githubusercontent.com/40122905/161617147-c47667cf-1746-4d73-8c10-9818cb95eaf1.mp4

https://user-images.githubusercontent.com/40122905/161617155-e69fce52-2d81-45b2-86ee-a418ee79cfe9.mp4

**Comment by Calyxman** [comment]
This has happened to me before too.

**Comment by NachosChipeados** [comment]
Can't replicate this issue on the newest Northstar version. Maybe it was fixed at some point?

**Comment by Zanieon** [comment]
Imma close this and assume the reports were due to nobody actually knowing servers can mod Frag nade to be thrown prematurely by changing their max cook time to a low value. Since nowdays people knows more that servers have the ability to alter certain weapon properties without clients needing to know, in my perspective this was never and issue, just a server modding the Frag Grenade max cook time.
