### ISSUE TITLE
Latency not being shown in the search UI

### ISSUE THREAD

**Issue by tniromin** [R2Northstar/Northstar#303]
### Bug
Im playing through Singapore servers which normally has a ping of 50-90.All the games I play have a ping of 300 and in the search UI the ping of the servers aren't displayed.Due to the high ping the gaming experience is ruined , I would have better chance of enjoying the game if I could know the ping of the server Im about to join.

### Steps to reproduce

1.In multiplayer menue goto play server search
2.observer the UI
  

### Specifications
  - Northstar version:1.9
  - Platform: steam[Origin link]

**Comment by GeckoEidechse** [comment]
The latency column in the server browser is a remnant from when were planning to allow clients to ping servers. The issue is that there's not really a way to do that without immediately giving away all game server IP addresses, making it easier to DDoS them.

IIRC our current plan is to use region tags to tell you which servers are closer to you but we're short staffed so progress is slow.

As a sidenote, there's a sister project to Northstar called [NorthstarCN](https://github.com/R2NorthstarCN) aimed at the Chinese community due to them having issues playing on default Northstar servers due to [GFW](https://en.wikipedia.org/wiki/Great_Firewall). Their playerbase is nearly as big as default Northstar IIRC.

Given your close geographic proximity it might be worth a shot, if you cannot find servers in your region.

**Comment by tniromin** [comment]
Okay bro thanks.Ill try to help the project if I get time .
Can you point how to get started if I wish to help
