### ISSUE TITLE
Can't play singleplayer on a no-client/offline copy

### ISSUE THREAD

**Issue by theolux** [R2Northstar/Northstar#394]
Hi,
I'm new to Northstar and would like to play it on my no-client/offline copy of the game to enjoy mods.  But when I try to continue my campaign it says "Invalid Name" and doesn't let me play. Any possible solution to this?
Thank you.

**Comment by pg9182** [comment]
That's been a known bug for a few releases now, and no, there isn't any solution for this currently (R2Northstar/NorthstarLauncher#360 is a WIP).

For now, I recommend you use vanilla for singleplayer.

**Comment by GeckoEidechse** [comment]
I'm closing this as (to my knowledge) we do not support offline copies for legal reasons. However this issue is not limited to offline copies so I created #403 which talks about the same issue in a general context.

So if #403 can get resolved, this issue here should also be fixed. As such I suggest keeping an eye on #403 :P
