### ISSUE TITLE
failed reading origin path!

### ISSUE THREAD

**Issue by foco21** [R2Northstar/Northstar#53]
The game is failing to read the origin path from wine.......

**Comment by sphynx-das-nomadisch** [comment]
I too have this issue, I do hope that it will be resolved soon. Hopefully, this comment may help the developers realize that this is a big problem for us Linux users.

**Comment by abarichello** [comment]
I'm running on Linux with no problems, try following this guide:
https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux

**Comment by sphynx-das-nomadisch** [comment]
Ah! I see, redirect Steam to launch Northstar under Proton rather then doing it manually through Wine. Thank you for the guide my friend!

**Comment by sphynx-das-nomadisch** [comment]
@abarichello Sorry to bother, but after trying the tutorial, it does launch Northstar, although it comes up with the file corrupt error. I have heard that a good way to rectify this is by launching Origin separately, but since I launch Origin through Steam I can not. Any way to fix the corruption error on Linux? (Also apologies for sort of derailing this issue thread)

**Comment by abarichello** [comment]
Sorry I have no idea. My current setup uses Lutris with Origin. You might want to check #6 and #1 if you haven't already
